<h1>Python libraries for data analysis</h1>


<li><b><span style="color:blue">Numpy</span></b>: supports numerical and array operations
<li><b><span style="color:blue">Scipy</span></b>: open source library for mathematics and scientific computing
<li><b><span style="color:blue">Pandas</span></b>: supports data manipulation and analysis
<li><b><span style="color:blue">Visualization libraries</span></b>: matplotlib, seaborne, bokeh, plotly, gmplot, and many others provide support for charts and graphs

<h1>numpy</h1>


<h2>Why numpy?</h2>
<li>Multi-dimensional arrays:
<li>Faster and more space efficient than lists 
<li>Can incorporate C/C++/Fortran code
<li>Linear algebra, Fourier transforms, Random number support



<h2>numpy array</h2>

In [4]:
import numpy as np
ax = np.array([1,2,3,4,5])
print(type(ax))

<class 'numpy.ndarray'>


<li>A numpy array has a data type associated with its elements
<li>and elements need to be of the same data type
<li>But an element could be an 'arbitrarily' complex object

In [5]:
np.array([1,2,'a'])

array(['1', '2', 'a'], dtype='<U21')

In [ ]:
np.array([{'a':1,'b':2},4])

<h2>Specifying the type</h2>
<h3>Useful when reading a text stream directly into a numerical array</h3>

<h4>The <i>dtype</i> attribute</h4>
<li>Stores the data type in the array
<li>numpy makes a best guess of the data type

In [ ]:
ax = np.array([[1,2,3,4],[5,6,7,8.3]])
ax.dtype

In [ ]:
ax = np.array([{'a':1,'b':2},4])
ax.dtype

In [ ]:
x=['1','2','3']
xi = np.array(x,'int')
xf = np.array(x,'float')
xs = np.array(x,'str')
print(xi,xf,xs,sep='\n')

<li>The <i>astype</i> function converts from one type to another


In [ ]:
ax = np.array([1,2,3,'4'])
print(ax.dtype)
ax.astype(int)

In [ ]:
ay = ax.astype(np.float128)
print(ay)
ay.dtype

<h2>Basic operations</h2>

<h4>statistical operations</h4>

In [ ]:
x = np.array([13,24,21.2,17.6,21.7],'float')
print(x.sum(),x.mean(),x.std(),sep='\n')

<h4>arrray arithmetic operations</h4>
<li><b>Important</b>: Arrays must be the same size!

In [ ]:
x = np.array([13,24,21.2,17.6,21.7],'float')
y = np.array([1,3,4,7,2],'float')
x - y

In [ ]:
x+y

In [ ]:
x*y

In [ ]:
x/y

<h2>Multi-dimensional arrays</h2>

In [ ]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
print(ax)

<h3>Indexing</h3>

In [ ]:
ax[1,3] #indexing

<h3>Slicing</h3>

In [ ]:
ax[1:3,:] 
# ax[1:3,2:4] #Intersection between ax[1:3,:] and ax[:,2:4]

<h3>Reshaping</h3>
<li>nd arrays can be reshaped as long as the total dimensionality is unchanged


In [ ]:
print(ax.shape)
ax.reshape(9,2)
# ax.reshape(10,3)

<h3>Creating nd arrays</h3>

<h4>Using the <i>array</i> function</h4>

In [ ]:
data = [[0,1,2,3,4],[5,6,7,8,9]]
data_array = np.array(data)
data_array

<h4>Using initializers</h4>

<li>The <i>arange</i> (array range) function


In [ ]:
ax = np.arange(10)
print(ax)
ay = np.array([np.arange(10),np.arange(10)])
print(ay)
ax.dtype

In [ ]:
ax = np.arange(10)**2
print(ax)

<li>The <i>ones</i> function creates an array of 1s (floats)

In [ ]:
ax = np.ones(10)
print(ax)
ax.dtype

In [ ]:
ax = np.array([[1,2,3,4],[5,6,7,8]])
ay = np.ones_like(ax)
ay

In [ ]:
ay = np.zeros_like(ax)
ay

<li>The <i>identity(n)</i> function creates an identity matrix of order n

In [ ]:
np.identity(10)

<li>The function <i>empty</i> creates an "empty" array
<li>Values in the array are "garbage" values

In [ ]:
np.empty([2,3],float)

<h3>Matrix multiplication</h3>


In [ ]:
ax = np.arange(10)
ay = np.array([ax,ax])
#Scalar multiplication
ay*2

In [ ]:
np.dot(ay,ay.reshape(10,2)) #Dot product

<h2>Lists vs numpy arrays</h2>
<li>Lists are heterogenous. Elements of a list can be of multiple types
<li>Numpy arrays are homogeneous. Elements can be of only one type
<li>Both are mutable
<li>Homogeneity makes indexed access faster and more memory efficient
<li>numpy are optimized for matrix operations
<li>numpy provides random number support


<h3>numpy arrays are homogeneous</h3>

<h3>numpy arrays are faster</h3>

In [ ]:
n=10
ax = np.array([np.arange(n)**2,np.arange(n)**3])
ay = ax.transpose()
print(ax)
print(ay)
np.dot(ax,ay)

<h4>Functionalize this</h4>


In [5]:
import datetime
import numpy as np

In [26]:
def dotproduct(n):
    ax = np.array([np.arange(n)**2,np.arange(n)**3])
    ay = ax.transpose()*5
    print(ax)
    print(ay)
#     return np.dot(ax,ay)
    
    start = datetime.datetime.now()
    np.dot(ax,ay)
    end = datetime.datetime.now()
    return end-start
    
dotproduct(10)    

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]
[[   0    0]
 [   5    5]
 [  20   40]
 [  45  135]
 [  80  320]
 [ 125  625]
 [ 180 1080]
 [ 245 1715]
 [ 320 2560]
 [ 405 3645]]


datetime.timedelta(0, 0, 18)

<h4>Do the same with python lists</h4>
<li>zip - takes n lists with length y and returns a list with y tuples of an item from each original list zip([a,b,c],[1,2,3]) returns [('a',1), ('b',2), ('c',3)]</li>
<li>asterisk(*) before a parameter unpacks it</li>
 

In [18]:
def dot_product_lists(n):
    x = [x**2 for x in range(n)]
    y = [x**3 for x in range(n)]
    ax = [x,y]
    ay = [list((e*5 for e in i)) for i in zip(*ax)]
    print(ax)
    print(ay)

    return [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)] for X_row in ax]
    start = datetime.datetime.now()
    [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)] for X_row in ax]
    end = datetime.datetime.now()
    return end-start
        
dot_product_lists(10)

[[0, 1, 4, 9, 16, 25, 36, 49, 64, 81], [0, 1, 8, 27, 64, 125, 216, 343, 512, 729]]
[[0, 0], [5, 5], [20, 40], [45, 135], [80, 320], [125, 625], [180, 1080], [245, 1715], [320, 2560], [405, 3645]]


[[76665, 604125], [604125, 4892025]]

<h4>Compare the two</h4>

In [12]:
for n in [10,100,1000,10000,1000000]:
    numpy_result = dotproduct(n)
    list_result = dot_product_lists(n)
    print(n,numpy_result,list_result,sep='\t')

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]
[[   0    0]
 [   5    5]
 [  20   40]
 [  45  135]
 [  80  320]
 [ 125  625]
 [ 180 1080]
 [ 245 1715]
 [ 320 2560]
 [ 405 3645]]
[[0, 1, 4, 9, 16, 25, 36, 49, 64, 81], [0, 1, 8, 27, 64, 125, 216, 343, 512, 729]]
[[0, 0], [5, 5], [20, 40], [45, 135], [80, 320], [125, 625], [180, 1080], [245, 1715], [320, 2560], [405, 3645]]
10	[[  76665  604125]
 [ 604125 4892025]]	[[76665, 604125], [604125, 4892025]]
[[     0      1      4      9     16     25     36     49     64     81
     100    121    144    169    196    225    256    289    324    361
     400    441    484    529    576    625    676    729    784    841
     900    961   1024   1089   1156   1225   1296   1369   1444   1521
    1600   1681   1764   1849   1936   2025   2116   2209   2304   2401
    2500   2601   2704   2809   2916   3025   3136   3249   3364   3481
    3600   3721   3844   3969   4096   4225   4356   4489   4624   4761
   

[[                 0                  1                  4 ...
        999994000009       999996000004       999998000001]
 [                 0                  1                  8 ...
  999991000026999973 999994000011999992 999997000002999999]]
[[                  0                   0]
 [                  5                   5]
 [                 20                  40]
 ...
 [      4999970000045 4999955000134999865]
 [      4999980000020 4999970000059999960]
 [      4999990000005 4999985000014999995]]


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



1000000	[[1734200423954522016 8397391398913303552]
 [8397391398913303552 -147968165976647904]]	[[999997500001666666666666500000, 833330833335416666666666250000000000], [833330833335416666666666250000000000, 714283214288214285714284880952380952500000]]


<h3>numpy indexing vs list indexing</h3>
<li>numpy arrays use direct indexing
<li>lists use chained indexing

In [13]:
ax = np.array([1,2,3,4,8,9])
x = [1,2,3,4,8,9]

#Extract the first and last elements from the numpy array into a single array
ax[[0,-1]]

#Extract the first and last elements from the list into a new list
#[x[0],x[-1]]

array([1, 9])

<h3>numpy slicing vs list slicing</h3>

In [14]:
ax = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
ax[1:3,1:3]


array([[22, 23],
       [32, 33]])

In [15]:
ax

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [ ]:
lx = [[11,12,13,14],[21,22,23,24],[31,32,33,34]]
#HELP!

<h2>batch operations on nd arrays</h2>
<li>numpy arrays allow the application of batch operations on all elements of an array
<li>without having to write a for loop or use an iterator
<li>by <i>vectorizing</i> operations, numpy is much faster than the slow for loop structure of python


<h3>batch: selecting elements using a boolean mask</h3>
<li> A boolean mask applies a condition to each element in turn
<li> And returns an array of boolean with
<ul>
<li> True for each value that satisfies the condition
<li> False for every other value

In [30]:
ax = np.array([1,4,7,9,2,3,10,11,34,2])
ax < 7

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

<h4>The mask can be applied as a selection operator on the array

In [31]:
ax[ax<7]

array([1, 4, 2, 3, 2])

<h4>The mask doesn't have to be constructed on the same array</h4>
<li>But the mask and the array should have the same dimensions

In [32]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
names[bonus > 130000]


array(['Bill', 'Sally'], dtype='<U8')

<h3>batch: arithmentic operations</h3>
<li>+, -, *, /, scalar multiplication do an element by element operation

In [33]:
ax = np.array([[1,2,3],[4,5,6]])
1/ax

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

<h3>batch: functional arithmetic operators</h3>

In [34]:
ax = np.array([4,9,2,4,0,25,0])
print(np.sum(ax>5))
print(np.count_nonzero(ax))
print(np.any(ax>10))
print(np.all(ax>0))

2
5
True
False


<h3>Logical operations with numpy</h3>
<li>logical_or
<li>logical_and

In [35]:
np.logical_and(bonus>90000.0, bonus<400000 )

array([ True, False, False,  True, False])

<h4>Boolean operators</h4>
<li>the numpy equivalent of "and" is "&"
<li>the numpy equivalent of "or" is "|"
<li>the numpy equivalent of "not" is "!"


In [36]:
print(np.sum(bonus[(bonus>50000) & (bonus < 200000)]))
print(np.sum(bonus[(names=="Bill") | (names == "Qing")]))
print(np.sum(bonus[(names!="Bill")]))
print(np.sum(bonus[~((names=="Bill") | (names == "Qing"))]))


150135.86
236191.8
632150.55
628259.31


<b>Problem</b> Calculate the mean and median bonus amount for all female employees with bonus less than $100,000

In [39]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
gender = np.array(['M','F','F','F','M'])

np.mean(bonus[(gender == 'F')])

193342.35

<b>Problem</b> Return an nd array containing the names of all female employees with bonus less than $100,000

In [40]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
gender = np.array(['M','F','F','F','M'])


<h3>batch: Selecting elements using where</h3>
<li><i>where</i> function creates a new array using a conditional expression
<li>Somewhat like the if function in an excel spreadsheet

<h2>axes</h2>
<li>The axis parameter tells numpy which axis to operate along

In [41]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ax = ax.reshape(3,4)
print(ax)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<h4>sum each column</h4>

In [ ]:
ax.sum(axis=0)

<h4>sum each row</h4>

In [ ]:
ax.sum(axis=1)

<h4>sum by depth</h4>

In [ ]:
ax=ax.reshape(2,3,2)
print(ax)
ax.sum(axis=2)

<h4>add an axis to an array</h4>


In [ ]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ax)
ax[:,np.newaxis]

<h4>Easy to add n-dimensions to an nd array using newaxis</h4>

In [ ]:
ax = ax.reshape(4,3)
ax[np.newaxis,np.newaxis,np.newaxis].shape

In [ ]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
np.where(ax%2==0,1,0)

<h2>Broadcasting</h2>
<li>arithmetic operations work element by element
<li>so both arrays have to be of the same length
<li><b>broadcasting</b> is used for arithmetic on arrays of different shapes

In [50]:
ax = np.array([1,2,3])
ay = np.array([3,2,1])
ax+ay

array([4, 4, 4])

<li>when one operand is a scalar, numpy works as if it has created a second array
<li>ax + 5 is equivalent to ax + np.array([5,5,5,])
<li>note the "as if" because it doesn't actually do that
<li>instead it <b>broadcasts</b> the 5 to each element of ax
<li>we can do this broadcasting on any dimensional array

In [51]:
ay = np.ones([3,3])
ay

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
ax = np.array([1,2,3])
ax + ay

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

<b>broadcasting</b> won't work when arrays are of incompatible dimensions

In [53]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ay = np.array([3,4,5])
ax + ay

ValueError: operands could not be broadcast together with shapes (12,) (3,) 

<h4>np.newaxis is useful here because we can convert ax into a 2D array</h4>

In [54]:
ax[:,np.newaxis] # + ay

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [55]:
#Broadcasting effectively does this:
ax[:,np.newaxis] + np.array([[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5]])

array([[ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17]])

<h4>We could also convert ay into a 2D array</h4>
<li>the result will be different (why?) 

In [56]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ay = np.array([3,4,5])
ay[:,np.newaxis] # +ax

array([[3],
       [4],
       [5]])

<h2>Fancy indexing</h2>
<li>numpy let's us work on indexed subsets of an nd array
<li>this lets us construct arbitrary subsets of an nd array in any dimension

In [57]:
ax = np.array([4,3,9,2,1,6])
ay = np.array([2,4])
ax[ay] # [ax[2], ax[4]]

array([9, 1])

In [58]:
ay = np.array([[2,4],[1,3]])
ax[ay]

array([[9, 1],
       [3, 2]])

<h4>multi-dimentional indexes</h4>
<li>In a 2-d, index, the index array is used to generate (row_number,col_number) pairs

In [59]:
ax = np.array([[23,34,21,34,22],[33,44,11,29,32],[14,90,10,20,17]])
rows = np.array([0,2])
cols = np.array([1,4])
ax[rows,cols] # [ax[0,1],ax[2,4]]

array([34, 17])

<h2>Universal functions</h2>
<li>functions that perform elementwise operations on arrays
<li>fast "wrapper" functions that produce scalar (or lower dimension) results
<li>sqrt, exp, add,maximum, minimum, abs, etc.
<li>https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [60]:
ax = np.array([1,2,3,4,5,6,7],float)
np.sqrt(ax)
#np.exp(ax)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131])

In [61]:
ay = np.arange(10,17)
np.add(ax,ay)
#np.maximum(ax,ay)

array([11., 13., 15., 17., 19., 21., 23.])

In [62]:
#linalg, a linear algebra module
#functions dealing with polynomials, differentials, etc

In [63]:
import scipy
scipy.nanmean(x)

4.5

<h3>Random number support in numpy</h3>

In [64]:
np.random.normal(size=10)
#np.random.normal(size=(100,100))
#np.random.exponential()
#np.random.exponential(1.0,size=(6,3))
#np.random.randint(-10,10,size=(9,9))

array([ 1.45333121, -1.17735587, -0.11729443,  0.12651255, -0.41511823,
        0.00519063,  0.00516612, -0.138471  ,  1.85372222,  0.83675393])